### PR TITLE
Fixes #201 - Fix loader workflow and improve error handling

### LINKED ISSUE #201: Parallel requests result in require resolutions with undefined values
Because the loader is waiting for definitions instead of implementations before calling the success handler it may pass `undefined` values for modules that are defined but not yet implemented.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

File: webpack.proxyPortal.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+					{
+						loader: 'babel-loader',
+						options: {},
+					},
+				],
+			},
+		],
+	},
+	devServer: {
+		port: 9090,
```
Comment (wincent) [inline webpack.proxyPortal.js]: This is the same port as the themes watcher uses. I wonder if we should be using the "portfinder" package to make sure we always get hold of *some* port even if the one we ask for isn't available.

File: package.json [hunk 2]
```diff
@@ -1,81 +1,84 @@
...
+		"package.json",
+		"README.md",
+		"webpack.config.js",
+		"src",
+		"bin",
+		"build",
+		"src"
+	],
+	"dependencies": {
+		"es6-promise": "^4.0.5"
```
Comment (jbalsas) [inline package.json]: I know this has been here for a long time, but it stood up right now since the file has been formatted. 

I think we could remove the promise polyfill right now and make this the responsability of calling code. That way, in DXP, for example, we can make sure we only load it on IE11 reducing the size of the loader considerably. That is, unless we're using something like cancellablepromise here... 🤔 

What do you think @wincent, @izaera?

File: src/loader/config.js [hunk 3]
```diff
@@ -104,17 +104,24 @@ export default class Config {
 
 	/**
 	 * Adds a module to the configuration with default field values if it
-	 * doesn't exist. Otherwise, returns the module.
+	 * doesn't exist. Otherwise, throws an exception.
 	 * @param {string} moduleName
+	 * @param {object} extraProps
```
Comment (jbalsas) [inline src/loader/config.js]: What are extraProps? Could we maybe add an example for this?

File: webpack.proxyPortal.js (hunk 1 above)
Comment (izaera) [reply webpack.proxyPortal.js]: In this case this doesn't pose any problem because if you are using this you are doing a very specific task and chances are that the port is available.

Also, using a free port means that the number will vary and it's easier to just remember that we usually use 9090.

File: src/loader/config.js [hunk 4]
```diff
@@ -140,12 +147,12 @@ export default class Config {
...
-	getModules(moduleNames = []) {
-		if (moduleNames.length > 0) {
-			return moduleNames.map(moduleName => this.getModule(moduleName));
-		} else {
+	getModules(moduleNames = undefined) {
+		if (moduleNames === undefined) {
 			return Object.values(this._modules);
 		}
+
+		return moduleNames.map(moduleName => this.getModule(moduleName));
```
[the remark this answers is not in the document]
Comment (izaera) [reply src/loader/config.js]: Mmm, nope. If you request a module that doesn't exist you get `undefined` in the resulting array.

[the remark this answers is not in the document]
Comment (izaera) [reply src/loader/config.js]: Let me check.

File: package.json (hunk 2 above)
Comment (izaera) [reply package.json]: We are using the resolvable promise which is somewhat exotic, but should work on top of the standard Promise. However, if we remove the polyfill we need to make sure nothing breaks...

Comment (wincent) [reply package.json]: That sounds reasonable to me. In other projects I've worked with the requirement was to "bring your own polyfill" for the very basic stuff, like Promises, if you needed it.

File: src/loader/config.js (hunk 3 above)
Comment (izaera) [reply src/loader/config.js]: I'll rename it to `moduleProperties` and explain what it is in JSDoc

File: package.json (hunk 2 above)
Comment (izaera) [reply package.json]: I've removed it in #203
